"""Intial migration

Revision ID: fd29c0e74f01
Revises: 
Create Date: 2021-02-11 19:46:40.550206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd29c0e74f01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('Location_name', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('Location_name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=70), nullable=True),
    sa.Column('prod_qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prod_name')
    )
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('loc', sa.String(length=70), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=70), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('product__movement',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('loc', sa.String(length=70), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product__movement')
    op.drop_table('report')
    op.drop_table('product')
    op.drop_table('location')
    # ### end Alembic commands ###
